### ISSUE TITLE
Would you know how to use this in swift?

### ISSUE THREAD

**Issue by teghzoraver** [mixdesign/AAShareBubbles#16]
Your design is awesome for this pod. I really want to use it but I am having trouble converting to swift. Do you have any idea?

**Comment by mixdesign** [comment]
Hi,
I haven't tested this in swift. What kind of problem you faced?

**Comment by teghzoraver** [comment]
Mainly problems with converting the code and initializing

**Comment by khuong291** [comment]
I've already implement it using swift. Just do like this:

let shareBubles: AAShareBubbles = AAShareBubbles.init(centeredInWindowWithRadius: 100)
    shareBubles.delegate = self
    shareBubles.bubbleRadius = 40
    shareBubles.sizeToFit()
    shareBubles.showFacebookBubble = true
    shareBubles.showTwitterBubble = true
    shareBubles.addCustomButtonWithIcon(UIImage(named: "twitter"), backgroundColor: UIColor.whiteColor(), andButtonId: 100)
    shareBubles.show()

**Comment by khuong291** [comment]
But I don't know why, I only create facebook and twitter bubble, but it shows 3 bubbles

**Comment by galblank** [comment]
that's why you see 3 buttons 
shareBubles.addCustomButtonWithIcon(UIImage(named: "twitter"), backgroundColor: UIColor.whiteColor(), andButtonId: 100)
