### ISSUE TITLE
DimBackground

### ISSUE THREAD

**Issue by Natelegreat1** [mixdesign/AAShareBubbles#17]
Hi!

I'm wondering if there is any way to control the background dimming functionality?
I would like there to be *more* contrast to show off how beautiful AAShareBubbles are! :)

**Comment by mixdesign** [comment]
Hi @Natelegreat1 

You may use these properties to set dim alpha and color:

// The fader view alpha, by default is 0.15
**@property(nonatomic, assign) CGFloat faderAlpha;**

// The fader view background color, default is black
**@property (nonatomic, strong) UIColor *faderColor;**

**Comment by Natelegreat1** [comment]
Amazing! Thank you!
By going through the code, I also stumbled upon `initCenteredInWindowWithRadius` -- you should definitely showcase ALL these features in the README :)
