### ISSUE TITLE
Only add 2 buttons, but it shows 3 buttons

### ISSUE THREAD

**Issue by khuong291** [mixdesign/AAShareBubbles#20]
I only add 2 buttons, but it shows 3 buttons.
let shareBubles: AAShareBubbles = AAShareBubbles.init(centeredInWindowWithRadius: 100)
shareBubles.delegate = self
shareBubles.bubbleRadius = 40
shareBubles.sizeToFit()
shareBubles.showFacebookBubble = true
shareBubles.showTwitterBubble = true
shareBubles.addCustomButtonWithIcon(UIImage(named: "twitter"), backgroundColor: UIColor.whiteColor(), andButtonId: 100)
shareBubles.show()

**Comment by mixdesign** [comment]
The answer to your question is [here](https://github.com/mixdesign/AAShareBubbles/issues/16#issuecomment-173065385)
